keys:
  - &users:
    - &leto 5E8B20D064B3BAF89608A64BDC6BCF810B5857A5
  - &systems:
    - &farstar age1vrqzzulyq0apr6hfr8l6sgzcrjqd2hcjzqp06ru3x9dphy6e4s6srsvgsv
creation_rules:
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
    - age:
      - *farstar
      pgp:
      - *leto

